name: Repository Events
on:
  push:
    branches:
      - main
      - "week-**"
      - "!MAIN-T-**"
    tags:
        - "v1.*"
  pull_request:
    types: [opened, assigned, synchronize, reopened]
  issues:
    types: [opened, edited]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4