name: Manually Triggered Workflow
on:
  workflow_dispatch:
    inputs:
      string:
        description: A string input
        type: string
        required: false
        default: "Default value"
      number:
        description: A number input
        type: number
        required: false
        default: 42
      boolean:
        description: A boolean input
        type: boolean
        required: false
        default: true
      choice:
        description: A choice input
        type: choice
        required: false
        default: "Choice 1"
        options:
          - Choice 1
          - Choice 2
          - Choice 3
      environment:
        description: An environment input
        type: environment
        required: false
        default: production

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "Number: ${{ inputs.number }}"
          echo "Option: ${{ inputs.choice }}"
          echo "Bool: ${{ inputs.boolean }}"
          echo "Environment: ${{ inputs.environment }}"
